### ISSUE TITLE
新增Rap功能

### ISSUE THREAD

**Issue by kikitte** [LXGMAX/SingJump#1]
总所周知，每当人们谈论到唱和跳，总会情不自禁联想到Rap，由此可见，唱跳Rap本身就是三位一体，缺一不可，因此建议新增Rap功能，用于俘获广大的爱好者们。

**Comment by LXGMAX** [comment]
> 总所周知，每当人们谈论到唱和跳，总会情不自禁联想到Rap，由此可见，唱跳Rap本身就是三位一体，缺一不可，因此建议新增Rap功能，用于俘获广大的爱好者们。

RapMusic是手机客户端，目前正在开发
